title: Sol Blog
author: ALL User
email: bethbang1004@naver.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Sol
  tagline: Planner & Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  portfolio_image:  "assets/portfolio.png"
  disqus_shortname: bethbang1004
  show_excerpts: true
  navigation:
    - title: Contents
      url: "https://bethbang1004.github.io"
    - title: Vue JS란 무엇인가요?
      url: "https://bethbang1004.github.io/vuejs/vue.js/%EA%B0%9C%EC%9A%94/2020/07/16/welcome-to-jekyll.html"
    - title: Vue.js 양방향 데이터 바인딩(Two-way Data Binding)이란...?
      url: "https://bethbang1004.github.io/vuejs/vue.js/%EC%96%91%EB%B0%A9%ED%96%A5_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B0%94%EC%9D%B8%EB%94%A9/2020/07/18/binding-welcome-to-jekyll.html"
    - title: Atom 설치하기 + github 연동하기
      url: "https://bethbang1004.github.io/github/atom/%EC%84%A4%EC%B9%98/2020/08/02/binding-welcome-to-jekyll.html"
    - title: Node.js 설치하기
      url: "https://bethbang1004.github.io/mac/node.js/%EC%84%A4%EC%B9%98/2020/08/03/binding-welcome-to-jekyll.html"
    - title: Google Play Console 개발자 등록
      url: "https://bethbang1004.github.io"
      

  # generate social links in footer
  social_links:
    github: bethbang1004
    linkedIn: bethbang1004
    instagram: bethbang1004

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
